# Generated by Django 3.2 on 2021-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['data_upload']},
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(max_length=300, upload_to='users'),
        ),
    ]
